x-base-service: &base-service
  image: dingolytics/dingolytics-backend:$APPLICATION_SERVER_TAG
  restart: unless-stopped
  volumes:
    - vector-etc:/etc/vector

x-base-environment: &base-environment
  LOG_LEVEL: INFO
  REDIS_URL: redis://redis:6379/0
  HUEY_URL: redis://redis:6379/0
  SQLALCHEMY_DATABASE_URI: postgresql://dingolytics:$POSTGRES_PASSWORD@postgres/dingolytics
  CSRF_ENFORCED: "true"
  GUNICORN_TIMEOUT: 60
  SECRET_KEY: $SECRET_KEY
  DATASOURCE_SECRET_KEY: $DATASOURCE_SECRET_KEY
  CLICKHOUSE_DB: dingolytics
  CLICKHOUSE_USER: dingolytics
  CLICKHOUSE_PASSWORD: $CLICKHOUSE_PASSWORD
  VECTOR_CONFIG_PATH: /etc/vector/vector.yaml
  VECTOR_INGEST_URL: $VECTOR_INGEST_URL

services:
  caddy:
    restart: unless-stopped
    build:
      context: ./etc/caddy
    environment:
      WEB_HOST: "$WEB_HOST"
      WEB_HOST_LETSENCRYPT_EMAIL: "$WEB_HOST_LETSENCRYPT_EMAIL"
    ports:
      # Ports for local testing:
      - "127.0.0.1:8100:8100"
      # Ports for production:
      # - "80:80"
      # - "443:443"
      # - "443:443/udp"
    cap_add:
      - NET_ADMIN
    volumes:
      - htdocs_data:/var/htdocs:ro
      - caddy_data:/data
      - caddy_config:/config

  vector:
    image: timberio/vector:0.42.X-alpine
    restart: unless-stopped
    environment:
      VECTOR_WATCH_CONFIG: /etc/vector/vector.yaml
    volumes:
      - vector-data:/var/lib/vector
      - vector-etc:/etc/vector:ro
    command: --watch-config

  postgres:
    image: postgres:15.10-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: dingolytics
      POSTGRES_USER: dingolytics
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    volumes:
      - pgdata15:/var/lib/postgresql/data

  redis:
    image: bitnami/keydb:6.3.4-debian-12-r6
    restart: unless-stopped
    environment:
      KEYDB_AOF_ENABLED: "yes"
      ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - keydb:/bitnami/keydb/data

  clickhouse:
    restart: unless-stopped
    build:
      context: ./etc/clickhouse
    cap_add:
      - NET_ADMIN
      - SYS_NICE
      - IPC_LOCK
    environment:
      CLICKHOUSE_DB: dingolytics
      CLICKHOUSE_USER: dingolytics
      CLICKHOUSE_PASSWORD: $CLICKHOUSE_PASSWORD
      CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: 1
      CLICKHOUSE_INIT_TIMEOUT: 60
    volumes:
      - clickhouse-data:/var/lib/clickhouse
      - clickhouse-logs:/val/log/clickhouse-server

  frontend:
    image: dingolytics/dingolytics:$APPLICATION_FRONTEND_TAG
    volumes:
      - htdocs_data:/var/www/dingolytics:ro

  app-server:
    <<: *base-service
    depends_on:
      - clickhouse
      - postgres
      - redis
    # ports:
    #   - 127.0.0.1:$SERVER_PORT:5000
    environment:
      <<: *base-environment
    command: run_server

  app-worker:
    <<: *base-service
    depends_on:
      - app-server
    environment:
      <<: *base-environment
    command: run_worker

  app-periodic:
    <<: *base-service
    depends_on:
      - app-server
    environment:
      <<: *base-environment
    command: run_periodic

volumes:
  clickhouse-data:
  clickhouse-logs:
  vector-data:
  vector-etc:
  pgdata15:
  keydb:
  caddy_data:
  caddy_config:
  htdocs_data:
